# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Ruandom"
author:              "Carlos Ruano"
